### ISSUE TITLE
有调用例子不？

### ISSUE THREAD

**Issue by terry8204** [SuperChrisliu/librtmp#2]
感谢 Super Chirs liu 辛苦付出，有调用例子不？
我调试，里面的字段
build 里面有 host port app streamname,
我看没地方使用app 这个字段，是否有用呢？

我调用格式：
rtmp://xxxx:1935/live/13000001111_1_1078
我得理解：
host = xxxx
port = 1935
app = live
streamname = 13000001111_1_1078
看代码里面有调用了 streamname,没见使用app的地方。

**Comment by SuperChrisliu** [comment]
app是需要的，只是当时目标是跑起来，所以很多测试代码。在与rtmp服务器connect之后，先handshake，成功后，需要给rtmp服务器发送[connectCommand](https://github.com/SuperChrisliu/librtmp/blob/354c79a3a85b36c7cc440945f5d08e85f28d5bee/src/main/java/com/tsingtech/librtmp/handler/SrsRtmpHandler.java#L27)，这个command里包含了tcUrl，代码里没从配置获取，你可以改成你的，也就是rtmp://xxxx:1935/live，之后发送命令的流程 createStream->publish，publish时需要streamname，[代码](https://github.com/SuperChrisliu/librtmp/blob/354c79a3a85b36c7cc440945f5d08e85f28d5bee/src/main/java/com/tsingtech/librtmp/handler/SrsRtmpHandler.java#L85)

**Comment by terry8204** [comment]
感谢 chris:
     昨晚改好了，跑起来了，在connectCommand里面调用 tcUrl
现在还是遇到 群主说的问题，没有java的aac 库，比较烦恼。

**Comment by SuperChrisliu** [comment]
我是参考这个项目https://github.com/begeekmyfriend/yasea，音频部分你也可以研究下

**Comment by terry8204** [comment]
我暂时还是用 ffmpeg 方式吧，只是量大了服务器要求很高，都是开进程。非常感谢 chirs.
